### ISSUE TITLE
Bug Found: Game Crashes After Level 15

### ISSUE THREAD

**Issue by NBumgardner** [MajorGrits/QuickSight#4]
# Introduction
Thank you for [hosting your project online with Microsoft Azure](http://quicksight.azurewebsites.net/)! Your ['Game' section](http://quicksight.azurewebsites.net/#/play) has a bug which can freeze the user's web page.
# Bug Description
It freezes if the player successfully wins levels 1 through 15, then clicks the button 'Next Level'. Once this button is clicked, the website freezes and will not refresh without first being killed. This poses a problem because the user is not warned ahead of time, and their high score is not saved in the ['High Scores' section](http://quicksight.azurewebsites.net/#/hscores). In other words, a player who completes levels 1 through 14 must lose level 15, otherwise their score cannot be saved.
# Possible Solutions
Below are three proposed workarounds to avoid freezing the webpage:
* The 'Next Level' button could be disabled or replaced after winning level 15.
* A new button could let the player retire early to submit their score.
* The game could congratulate the user for playing, which creates a positive possible ending to the game.

Addressing this bug could improve some users' experiences, and increase their chances of recommending the game to others.

**Comment by MajorGrits** [comment]
Nice catch. I'll take a look immediately.

**Comment by MajorGrits** [comment]
Ok the issue is that on that level all the pictures must be shown so on the playGame::randomizePictureSet function it takes the system too long to randomly insert all the pictures at that stage so the browser effectively kills it before it blows up. I'll just change it so that the randomizePictureSet is more optimized for the higher picture counts and when all the images need to be displayed I'll just add a function that inserts every picture possible in a quick loop.

**Comment by MajorGrits** [comment]
Problem is fixed, levels work as intended.

**Comment by NBumgardner** [comment]
Levels 16-18 have a 8x6 grid with 1 more centered below. Level 19 does not have a button to progress, yet correctly saves high scores. The high scores list shows the top ten highest scores. The game no longer crashes, nice work.
